Repository Unibeautify/unibeautify, pull requests merged in 2018-04, with the labels that each got.

#63 WIP: Dependency manager
  .codeclimate.yml
  .node-version
  .travis.yml
  .unibeautifyrc.yml
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  README.md
  __mocks__/fakedep/index.js
  __mocks__/fakedep/package.json
  __mocks__/requireg-global-fakedep/index.js
  __mocks__/requireg-global-fakedep/package.json
  jest.config.js
  package-lock.json
  package.json
  scripts/update-languages.ts
  src/DependencyManager/Dependency.ts
  src/DependencyManager/DependencyFactory.ts
  src/DependencyManager/DependencyManager.ts
  src/DependencyManager/ExecutableDependency.ts
  src/DependencyManager/NodeDependency.ts
  src/DependencyManager/Version.ts
  src/DependencyManager/index.ts
  src/InlineFlagManager.ts
  src/beautifier.ts
  src/index.ts
  test/DependencyManager/DependencyManager.spec.ts
  test/DependencyManager/ExecutableDependency.spec.ts
  test/DependencyManager/NodeDependency.spec.ts
  test/DependencyManager/Version.spec.ts
  test/InlineFlagManager.spec.ts
  test/beautifier/dependency.spec.ts
  test/beautifier/options.spec.ts
  test/setupTests.js
  tsconfig.json
Labels: enhancement, in progress

#72 See #58. Improve Dependency not installed error message
  src/DependencyManager/Dependency.ts
  src/DependencyManager/NodeDependency.ts
  test/DependencyManager/DependencyManager.spec.ts
  test/DependencyManager/ExecutableDependency.spec.ts
  test/DependencyManager/NodeDependency.spec.ts
Labels: enhancement

#73 Remove lodash methods
  src/beautifier.ts
  src/utils.ts
  test/InlineFlagManager.spec.ts
  test/beautifier/pipeline.spec.ts
  test/index.spec.ts
  test/utils.spec.ts
Labels: enhancement, high priority

#77 Add support for configuration of dependencies
  .vscode/launch.json
  package-lock.json
  src/DependencyManager/Dependency.ts
  src/DependencyManager/DependencyFactory.ts
  src/DependencyManager/DependencyManager.ts
  src/DependencyManager/ExecutableDependency.ts
  src/DependencyManager/NodeDependency.ts
  src/beautifier.ts
  src/utils.ts
  test/DependencyManager/DependencyManager.spec.ts
  test/DependencyManager/ExecutableDependency.spec.ts
  test/DependencyManager/NodeDependency.spec.ts
  test/beautifier/beautifier.spec.ts
  test/beautifier/dependency.spec.ts
Labels: add option, enhancement, high priority

#82 Refactor beautifier.ts
  package-lock.json
  package.json
  src/LanguageManager.ts
  src/OptionsManager.ts
  src/beautifier.ts
  src/utils.ts
  test/beautifier/languages.spec.ts
Labels: enhancement, high priority

#86 Close #48. Add prefer_beautifier_config option
  package-lock.json
  package.json
  src/LanguageManager.ts
  src/OptionsManager.ts
  src/beautifier.ts
  src/utils.ts
  test/beautifier/beautifier.spec.ts
  test/beautifier/config.spec.ts
  test/beautifier/dependency.spec.ts
  test/beautifier/languages.spec.ts
  test/beautifier/options.spec.ts
  test/beautifier/pipeline.spec.ts
  test/index.spec.ts
  tslint.json
Labels: add option, enhancement, high priority
